num_samples: 1000
labels: [A, B, C, L]

# eval conf
n_eval: 1

# Env conf
env:
  reward_structure: quiz
  add_step_reward_penalty: False
  add_detector_state_reward_for_quiz: False
  step_reward_penalty: 0.01
  detector_reward: 1
  quiz_positive_reward: 1
  quiz_negative_reward: -1
  max_steps: 20
  blicket_dim: 3
  quiz_disabled_steps: 5                       # forced exploration steps
  hypotheses: |
    from causal_env_v0 import ABdisj, BCdisj, ACdisj, Adisj
    hypotheses = [
      Adisj
    ]